// Generated by CoffeeScript 1.6.3
(function() {
  var CityAroundResearch;

  CityAroundResearch = (function() {
    function CityAroundResearch(geolocation, callback, proximity) {
      var searchParams, that;
      this.geolocation = geolocation;
      this.callback = callback != null ? callback : (function() {});
      this.proximity = proximity != null ? proximity : 'asc';
      searchParams = {
        lat: this.geolocation.getLat(),
        long: this.geolocation.getLong(),
        results: 10,
        proximity: this.proximity
      };
      that = this;
      $.get('http://thelycornweather.sebacmieu.fr/search/city.php', searchParams, function(data) {
        if (typeof console !== "undefined" && console !== null) {
          console.log(data);
        }
        return that.callback(data);
      }, 'JSON');
    }

    return CityAroundResearch;

  })();

  if (!window.lycorn) {
    window.lycorn = {};
  }

  window.lycorn.CityAroundResearch = CityAroundResearch;

}).call(this);

//# sourceMappingURL=CityAroundResearch.map
