// Generated by CoffeeScript 1.6.3
(function() {
  var GeolocationProvider;

  GeolocationProvider = (function() {
    function GeolocationProvider(callback) {
      this.callback = callback != null ? callback : (function() {});
      this.doc = jQuery(document);
      this.geolocationOpts = {
        enableHighAccuracy: true,
        maximumAge: 0,
        timeout: 30
      };
      if (navigator.geolocation) {
        this.searchWithGPS();
      } else {
        this.searchWithoutGPS();
      }
    }

    GeolocationProvider.prototype.searchWithGPS = function() {
      var that;
      that = this;
      navigator.geolocation.getCurrentPosition(function(position) {
        var geocodingParams, lat, long, provider;
        provider = that;
        lat = position.coords.latitude;
        long = position.coords.longitude;
        geocodingParams = {
          latlng: lat + ',' + long,
          sensor: 'true'
        };
        return $.get('http://maps.googleapis.com/maps/api/geocode/json', geocodingParams, function(data) {
          var city, component, country, type, _i, _len, _ref;
          for (component in data.results.address_components) {
            _ref = component.types;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              type = _ref[_i];
              if (type === "locality") {
                city = component.short_name;
              }
              if (type === "country") {
                country = component.short_name;
              }
            }
          }
          provider.buildLocation(lat, long, city, country, 'GPS');
        }, 'JSON');
      }, this.searchWithoutGPSAsFallback(this), this.geolocationOpts);
    };

    GeolocationProvider.prototype.searchWithoutGPSAsFallback = function(scope) {
      var context, temp;
      context = scope;
      return temp = function() {
        return context.searchWithoutGPS.apply(context);
      };
    };

    GeolocationProvider.prototype.searchWithoutGPS = function() {
      var provider;
      provider = this;
      $.get('http://ipinfo.io/json', function(data) {
        var geocodingParams, lat, long, _tmp;
        _tmp = data.loc.split(',');
        lat = _tmp[0];
        long = _tmp[1];
        if (!data.city || !data.country) {
          geocodingParams = {
            latlng: lat + ',' + long,
            sensor: 'true'
          };
          $.get('http://maps.googleapis.com/maps/api/geocode/json', geocodingParams, function(data) {
            var city, component, country, type, _i, _len, _ref;
            for (component in data.results.address_components) {
              _ref = component.types;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                type = _ref[_i];
                if (type === "locality") {
                  city = component.short_name;
                }
                if (type === "country") {
                  country = component.short_name;
                }
              }
            }
            provider.buildLocation(lat, long, city, country, 'GPS');
          });
        }
        provider.buildLocation(lat, long, data.city, data.country, 'IP');
      }, 'JSON');
    };

    GeolocationProvider.prototype.buildLocation = function(lat, long, city, country, type) {
      var location;
      location = new lycorn.Geolocation(lat, long, city, country, type);
      this.callback(location);
    };

    if (!window.lycorn) {
      window.lycorn = {};
    }

    window.lycorn.GeolocationProvider = GeolocationProvider;

    return GeolocationProvider;

  })();

}).call(this);

//# sourceMappingURL=GeolocationProvider.map
