// Generated by CoffeeScript 1.6.3
(function() {
  var Geolocation;

  Geolocation = (function() {
    function Geolocation(lat, long, cityName, country, type) {
      this.lat = lat;
      this.long = long;
      this.cityName = cityName;
      this.country = country;
      this.type = type != null ? type : 'ip';
    }

    Geolocation.prototype.getLat = function() {
      return this.lat;
    };

    Geolocation.prototype.getLong = function() {
      return this.long;
    };

    Geolocation.prototype.getCityName = function() {
      return this.cityName;
    };

    Geolocation.prototype.country = function() {
      return this.country;
    };

    return Geolocation;

  })();

  if (!window.lycorn) {
    window.lycorn = {};
  }

  window.lycorn.Geolocation = Geolocation;

}).call(this);

//# sourceMappingURL=Geolocation.map
