// Generated by CoffeeScript 1.6.3
(function() {
  var Loader;

  Loader = (function() {
    Loader["default"] = {
      nbItems: 10,
      speed: 1000
    };

    function Loader(element, options) {
      this.element = element;
      this.animateIncrease();
    }

    Loader.prototype.animateIncrease = function() {
      var that;
      that = this;
      return this.element.animate({
        width: '100%'
      }, 'slow', 'swing', function() {
        return setTimeout(function() {
          return that.animateDecrease();
        }, 1000);
      });
    };

    Loader.prototype.animateDecrease = function() {
      var that;
      that = this;
      return this.element.animate({
        width: '0%'
      }, 'slow', 'swing', function() {
        return setTimeout(function() {
          return that.animateIncrease();
        }, 1000);
      });
    };

    return Loader;

  })();

  window.lycornLoader = Loader;

}).call(this);

//# sourceMappingURL=Loader.map
