// Generated by CoffeeScript 1.6.3
(function() {
  window.myApp = angular.module('myApp', []);

  window.myApp.controller('SearchResults', function($scope) {
    $scope.locations = [];
    $scope.arriving = true;
    $scope.doshow = {};
    $scope.getTempIndicatorClass = function(temp) {
      if (temp < 6) {
        return 'cold';
      }
      if (temp < 22) {
        return 'warm';
      }
      return 'hot';
    };
    return $scope.getMetroClass = function(index) {
      var availableClasses;
      availableClasses = ['panel-primary', 'panel-success', 'panel-warning', 'panel-danger', 'panel-info'];
      return availableClasses[index % 5];
    };
  });

}).call(this);

//# sourceMappingURL=SearchResults.map
