//@ sourceMappingURL=CityAroundSearchEngine.map
// Generated by CoffeeScript 1.6.1
(function() {
  var CityAroundSearchEngine;

  CityAroundSearchEngine = (function() {

    function CityAroundSearchEngine(currentLocation, googleMap) {
      var request, service;
      this.currentLocation = currentLocation;
      this.googleMap = googleMap;
      service = new google.maps.places.PlacesService(this.googleMap.getGoogleMap());
      request = {
        location: this.currentLocation,
        radius: '500',
        types: ['museum']
      };
      service.nearbySearch(request, function(result, status) {
        return typeof console !== "undefined" && console !== null ? console.log(result, status) : void 0;
      });
    }

    return CityAroundSearchEngine;

  })();

  if (window.lycorn === void 0) {
    window.lycorn = {};
  }

  window.lycorn.CityAroundSearchEngine = CityAroundSearchEngine;

}).call(this);
