//@ sourceMappingURL=GoogleMap.map
// Generated by CoffeeScript 1.6.1
(function() {
  var GoogleMap;

  GoogleMap = (function() {

    function GoogleMap(mapCenter) {
      var map;
      this.mapCenter = mapCenter;
      map = document.createElement('div');
      map.className = 'googleMap';
      document.getElementById('mapsContainer').appendChild(map);
      this.render();
      this.renderPoint(this.mapCenter);
      return this;
    }

    GoogleMap.prototype.render = function() {
      var mapOptions;
      mapOptions = {
        center: this.mapCenter,
        zoom: 16
      };
      return this.gmap = new google.maps.Map(document.getElementsByClassName('googleMap')[0], mapOptions);
    };

    GoogleMap.prototype.renderPoint = function(point) {
      var markerData;
      markerData = {
        position: point,
        map: this.gmap
      };
      return new google.maps.Marker(markerData);
    };

    GoogleMap.prototype.getGoogleMap = function() {
      return this.gmap;
    };

    return GoogleMap;

  })();

  if (window.lycorn === void 0) {
    window.lycorn = {};
  }

  window.lycorn.GoogleMap = GoogleMap;

}).call(this);
