//@ sourceMappingURL=GPSLocalisator.map
// Generated by CoffeeScript 1.6.1
(function() {
  var GPSLocalisator;

  GPSLocalisator = (function() {

    GPSLocalisator.currentRenderedMap = 0;

    GPSLocalisator.geolocationOpts = {
      enableHighAccuracy: true,
      maximumAge: 0,
      timeout: 30
    };

    function GPSLocalisator() {
      var that;
      if (navigator.geolocation) {
        that = this;
        navigator.geolocation.getCurrentPosition(function(position) {
          that.useGeolocation(position);
        }, this.geolocationFallback, this.geolocationOpts);
      }
    }

    GPSLocalisator.prototype.useGeolocation = function(position) {
      var citySearch, googleMap, latitude, longitude;
      latitude = position.coords.latitude;
      longitude = position.coords.longitude;
      this.currentLocation = new google.maps.LatLng(latitude, longitude);
      if (typeof console !== "undefined" && console !== null) {
        console.log('Coord found ! ', latitude, longitude);
      }
      googleMap = new lycorn.GoogleMap(this.currentLocation);
      citySearch = new lycorn.CityAroundSearchEngine(this.currentLocation, googleMap);
    };

    GPSLocalisator.prototype.geolocationFallback = function() {
      return typeof console !== "undefined" && console !== null ? console.log('Geolocation fallback') : void 0;
    };

    return GPSLocalisator;

  })();

  if (window.lycorn === void 0) {
    window.lycorn = {};
  }

  window.lycorn.GPSLocalisator = GPSLocalisator;

}).call(this);
